# Generated by Django 3.0.7 on 2022-03-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220307_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='itemname',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
