# Generated by Django 3.0.7 on 2022-03-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220308_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='itemname',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
