# Generated by Django 3.0.7 on 2022-03-08 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_items_itemsdtaa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='itemsdtaa',
        ),
    ]
