# Generated by Django 3.0.7 on 2022-03-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220303_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
