# Generated by Django 3.0.7 on 2022-03-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_items_itemsdtaa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='itemname',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
